name: triple_switch
description: "Three-position switch has three states ON - WAIT - OFF. 
WAIT state is a state awaiting finish heavy operation like getting information from net. 
ON / OFF is a usual state of switch"

version: 1.0.0

repository: https://github.com/leocoderu/triple_switch
homepage: https://leocode.ru

topics:
  - widgets

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^5.1.1

screenshots:
  - description: Triple switch logo.
    path: screenshots/logo.png
