name: triple_switch
description: "Triple switch has three states ON - WAIT - OFF. 
ON / OFF is a regular state of switch, WAIT is a state awaiting finish heavy operation"

version: 1.1.4

repository: https://github.com/leocoderu/triple_switch
homepage: https://leocode.ru

topics:
  - widgets

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^5.1.1

screenshots:
  - description: Triple switch logo.
    path: screenshots/logo.png
